name: Remote Dispatch Action Initiator
#test
on: [push]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.T }}
          event-type: update
          repository: Snail-IDE/snail-ide.github.io
      - name: Repository Dispatch2
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.T }}
          event-type: update
          repository: PenguinMod/PenguinMod-Packager
